name: Caddy Custom
version: 6e553c4
slug: caddy-custom
description: Cusomizable caddy server
url: https://github.com/datf/hassio-caddy-custom
arch:
- amd64
- aarch64
startup: services
host_network: true
map:
- addon_config:rw
- ssl:rw
options:
  args: []
  env_vars: []
  plugins: []
  log_level: info
schema:
  plugins:
  - match(^github\.com/.*)
  args:
  - str
  env_vars:
  - name: str
    value: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)
environment:
  LOG_FORMAT: '{LEVEL}: {MESSAGE}'
init: false
image: ghcr.io/datf/caddy-custom
