---
channel: edge
apps:
  caddy-custom:
    repository: datf/hassio-caddy-custom
    target: caddy-custom
    image: ghcr.io/datf/caddy-custom
  dante:
    repository: datf/app-dante
    target: dante
    image: ghcr.io/datf/dante
  dante-to-wireguard:
    repository: datf/app-dante-to-wireguard
    target: dante-to-wireguard
    image: ghcr.io/datf/dante-to-wireguard
