name: Dante to Wireguard
version: '3788928'
slug: dante-to-wireguard
description: SOCKS proxy server with VPN exit
url: https://github.com/datf/app-dante-to-wireguard
arch:
- amd64
- aarch64
startup: services
ports:
  1080/tcp: null
  1080/udp: null
ports_description:
  1080/tcp: SOCKS proxy TCP
  1080/udp: SOCKS proxy UDP
privileged:
- NET_ADMIN
- NET_RAW
devices:
- /dev/net/tun
map:
- addon_config:rw
options:
  log_level: info
  require_username_auth: false
  credentials:
    username: admin
    password: ''
  mtu: 1280
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  require_username_auth: bool
  credentials:
    username: str?
    password: password?
  mtu: int(1280,1500)?
init: false
image: ghcr.io/datf/dante-to-wireguard
