name: Dante
version: ece9b03
slug: dante
description: SOCKS proxy server
url: https://github.com/datf/app-dante
arch:
- amd64
- aarch64
startup: services
host_network: true
map:
- addon_config:rw
options:
  log_level: info
  network_interface: ''
  require_username_auth: false
  credentials:
    username: admin
    password: ''
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  network_interface: device(subsystem=net)
  require_username_auth: bool
  credentials:
    username: str?
    password: password?
init: false
image: ghcr.io/datf/dante
