---
name: Repository Update

# yamllint disable-line rule:truthy
on:
  repository_dispatch:
    types: ["update"]

permissions:
  contents: read

jobs:
  updater:
    name: Updater for ${{ github.event.client_payload.app }}
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git Author
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Run repository updater
        uses: datf/repository-updater@c2a8e7bdec9b38102666ab97c9f56cf624463ff6
        with:
          app: ${{ github.event.client_payload.app }}
          repository: ${{ github.repository }}
          token: ${{ secrets.UPDATER_TOKEN }}
